/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.personalproj;

import javax.swing.BorderFactory;
import javax.swing.UIManager;

/**
 *
 * @author aaron
 */
public class PosFrame extends javax.swing.JFrame {

    /**
     * Creates new form PosFrame
     */
    public PosFrame() {
        initComponents();
    }
    int total = 0;
    int price;
    String selected;
    String display = "";
    boolean isActive = true;
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        burgerImg = new javax.swing.JButton();
        juiceBtn = new javax.swing.JButton();
        pizzaBtn = new javax.swing.JButton();
        steakBtn = new javax.swing.JButton();
        saladBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        quantityTxt = new javax.swing.JTextField();
        lblChosen = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Items");
        setResizable(false);

        burgerImg.setIcon(new javax.swing.ImageIcon("C:\\Users\\aaron\\Documents\\NetBeansProjects\\PersonalProj\\imgs\\burger (1).jpg")); // NOI18N
        burgerImg.setBorder(null);
        burgerImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                burgerImgMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                burgerImgMouseExited(evt);
            }
        });
        burgerImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                burgerImgActionPerformed(evt);
            }
        });

        juiceBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\aaron\\Documents\\NetBeansProjects\\PersonalProj\\imgs\\juice.jpg")); // NOI18N
        juiceBtn.setBorder(null);
        juiceBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                juiceBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                juiceBtnMouseExited(evt);
            }
        });
        juiceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juiceBtnActionPerformed(evt);
            }
        });

        pizzaBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\aaron\\Documents\\NetBeansProjects\\PersonalProj\\imgs\\pizza.jpg")); // NOI18N
        pizzaBtn.setBorder(null);
        pizzaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pizzaBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pizzaBtnMouseExited(evt);
            }
        });
        pizzaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pizzaBtnActionPerformed(evt);
            }
        });

        steakBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\aaron\\Documents\\NetBeansProjects\\PersonalProj\\imgs\\steak.jpg")); // NOI18N
        steakBtn.setBorder(null);
        steakBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                steakBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                steakBtnMouseExited(evt);
            }
        });
        steakBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                steakBtnActionPerformed(evt);
            }
        });

        saladBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\aaron\\Documents\\NetBeansProjects\\PersonalProj\\imgs\\salad.jpg")); // NOI18N
        saladBtn.setBorder(null);
        saladBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saladBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saladBtnMouseExited(evt);
            }
        });
        saladBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saladBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("₱ 250");

        jLabel2.setText("₱ 70");

        jLabel3.setText("₱470");

        jLabel4.setText("₱ 120");

        jLabel5.setText("₱1500");

        jLabel6.setText("Enter Quantity: ");

        lblChosen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        textArea.setEditable(false);
        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        jButton1.setText("Confirm Order");

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel1)
                        .addGap(128, 128, 128)
                        .addComponent(jLabel2)
                        .addGap(134, 134, 134)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(127, 127, 127)
                        .addComponent(jLabel5)
                        .addGap(57, 57, 57))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(burgerImg)
                        .addGap(15, 15, 15)
                        .addComponent(juiceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pizzaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(saladBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(steakBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(addBtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(quantityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblChosen, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(223, 223, 223)
                                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(burgerImg)
                    .addComponent(juiceBtn)
                    .addComponent(pizzaBtn)
                    .addComponent(saladBtn)
                    .addComponent(steakBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2))
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(13, 13, 13)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblChosen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(addBtn)
                        .addGap(47, 47, 47)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitBtn)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void juiceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juiceBtnActionPerformed
        // TODO add your handling code here:
        lblChosen.setText("Orange Juice:");
        selected = "Juice";
        price = 70;
    }//GEN-LAST:event_juiceBtnActionPerformed

    private void burgerImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_burgerImgActionPerformed
        // TODO add your handling code here:
        lblChosen.setText("Burger:");
        selected = "Burger";
        price = 250;
    }//GEN-LAST:event_burgerImgActionPerformed

    private void pizzaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pizzaBtnActionPerformed
        // TODO add your handling code here:
        lblChosen.setText("Pizza:");
        selected = "Pizza";
        price = 470;
    }//GEN-LAST:event_pizzaBtnActionPerformed

    private void saladBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saladBtnActionPerformed
        // TODO add your handling code here:
        lblChosen.setText("Salad:");
        selected = "Salad";
        price = 120;
    }//GEN-LAST:event_saladBtnActionPerformed

    private void steakBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_steakBtnActionPerformed
        // TODO add your handling code here:
        lblChosen.setText("Salad:");
        selected = "Steak";
        price = 1500;
    }//GEN-LAST:event_steakBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        int currentQuant = Integer.parseInt(quantityTxt.getText());
        int currentPrice = 0;
        for(int i = 1; i<=currentQuant;i++)
        {
            currentPrice+=price;
        }
        
        total+=currentPrice;
        
        
        display += currentQuant + " x " + selected + "        ₱"+currentPrice +"\n";
        textArea.setText(display+"\nTotal: " +total);
        quantityTxt.setText(null);
        
    }//GEN-LAST:event_addBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void burgerImgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_burgerImgMouseEntered
        // TODO add your handling code here:
        burgerImg.setBorder(BorderFactory.createEtchedBorder(0));
    }//GEN-LAST:event_burgerImgMouseEntered

    private void burgerImgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_burgerImgMouseExited
        // TODO add your handling code here:
        burgerImg.setBorder(null);
    }//GEN-LAST:event_burgerImgMouseExited

    private void juiceBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_juiceBtnMouseEntered
        // TODO add your handling code here:
        juiceBtn.setBorder(BorderFactory.createEtchedBorder(0));
    }//GEN-LAST:event_juiceBtnMouseEntered

    private void pizzaBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pizzaBtnMouseEntered
        // TODO add your handling code here:
        pizzaBtn.setBorder(BorderFactory.createEtchedBorder(0));
    }//GEN-LAST:event_pizzaBtnMouseEntered

    private void saladBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saladBtnMouseEntered
        // TODO add your handling code here:
        saladBtn.setBorder(BorderFactory.createEtchedBorder(0));
    }//GEN-LAST:event_saladBtnMouseEntered

    private void steakBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_steakBtnMouseEntered
        // TODO add your handling code here:
        steakBtn.setBorder(BorderFactory.createEtchedBorder(0));
    }//GEN-LAST:event_steakBtnMouseEntered

    private void juiceBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_juiceBtnMouseExited
        // TODO add your handling code here:
        juiceBtn.setBorder(null);
    }//GEN-LAST:event_juiceBtnMouseExited

    private void pizzaBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pizzaBtnMouseExited
        // TODO add your handling code here:
        pizzaBtn.setBorder(null);
    }//GEN-LAST:event_pizzaBtnMouseExited

    private void saladBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saladBtnMouseExited
        // TODO add your handling code here:
        saladBtn.setBorder(null);
    }//GEN-LAST:event_saladBtnMouseExited

    private void steakBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_steakBtnMouseExited
        // TODO add your handling code here:
        steakBtn.setBorder(null);
    }//GEN-LAST:event_steakBtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        String str = "com.formdev.flatlaf.themes.FlatMacDarkLaf";
        try
        {
            UIManager.setLookAndFeel(str);
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PosFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton burgerImg;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton juiceBtn;
    private javax.swing.JLabel lblChosen;
    private javax.swing.JButton pizzaBtn;
    private javax.swing.JTextField quantityTxt;
    private javax.swing.JButton saladBtn;
    private javax.swing.JButton steakBtn;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
